FROM mysql:5.7.22                                                                                                                                             

MAINTAINER FLLab

ENV MYSQL_ROOT_PASSWORD=123456 MYSQL_DATABASE=my_db MYSQL_USER=Jim MYSQL_PASSWORD=123456 MYSQL_TABLE=userinfo

EXPOSE 3306

RUN echo " \
     CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\` CHARACTER SET utf8 COLLATE utf8_general_ci;\
     use ${MYSQL_DATABASE}; \
     grant all privileges on \`${MYSQL_DATABASE}\`.* to '${MYSQL_USER}'@'%' identified by '${MYSQL_PASSWORD}'; \
     flush privileges; \
     use ${MYSQL_DATABASE}; \
     CREATE TABLE IF NOT EXISTS \`${MYSQL_TABLE}\`( \
       \`No\` VARCHAR(40) NOT NULL,\
       \`id\` INT UNSIGNED AUTO_INCREMENT,\
       \`SourceId\` VARCHAR(100) NOT NULL,\
       \`ReceiveId\` VARCHAR(40) NOT NULL,\
       \`ServerId\` VARCHAR(40) NOT NULL,\
       \`Value\` TEXT NOT NULL,\
       \`Tx_Id\` VARCHAR(64) NOT NULL,\
       \`MyTime\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\
       \`Flag\` boolean  NOT NULL,\
       PRIMARY KEY ( \`id\` )\
     )ENGINE=InnoDB DEFAULT CHARSET=utf8;" > /docker-entrypoint-initdb.d/init.sql

