FROM mysql:5.7.22

MAINTAINER FLLab

EXPOSE 3306

RUN echo " \
     use mysql; \
     grant all privileges on \`${MYSQL_DATABASE}\`.* to 'Jim'@'%' identified by '123456'; \
     flush privileges; \
     use ${MYSQL_DATABASE}; \
     CREATE TABLE IF NOT EXISTS \`${MYSQL_TABLE}\`( \
       \`id\` INT UNSIGNED AUTO_INCREMENT,\
       \`SourceId\` VARCHAR(100) NOT NULL,\
       \`ReceiveId\` VARCHAR(40) NOT NULL,\
       \`ServerId\` VARCHAR(40) NOT NULL,\
       \`Value\` TEXT NOT NULL,\
       \`Tx_Id\` VARCHAR(64) NOT NULL,\
       \`MyTime\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\
       \`Flag\` boolean  NOT NULL,\
       PRIMARY KEY ( \`id\` )\
     )ENGINE=InnoDB DEFAULT CHARSET=utf8;\
   update userinfo set Flag = True where ReceiveId = 'b' and Flag = false;" > /docker-entrypoint-initdb.d/init.sql 
