version: '2'

services:

  org1_sdk:
    container_name: org1_sdk
    image: fabric/sdk:0.1
    ports: 
      - 4000:4000
    volumes:
      - ../org1/network-config.yaml:/FLLab/org/artifacts/network-config.yaml
      - ../org1/org.yaml:/FLLab/org/artifacts/org.yaml
      - ../org1/src/:/FLLab/org/artifacts/src/
      - ./channel-artifacts/channel.tx:/FLLab/org/artifacts/channel/channel.tx
      - ./crypto-config/:/FLLab/org/artifacts/channel/crypto-config/
      - ./bootstrap.sh:/FLLab/org/bootstrap.sh
    environment:
      - NODE_ROLE=create
      - NODE_NAME=peer0
      - NODE_ORG=Org1
      - NODE_INIT_USER=Jim1
      - NODE_FULLNAME=peer0.org1.example.com
      - LISTEN_HOSTNAME=192.168.1.205

    working_dir: /FLLab/org
    command: /bin/bash bootstrap.sh 

  org2_sdk:
    container_name: org2_sdk
    image: fabric/sdk:0.1
    ports:
      - 4001:4000
    volumes:
      - ../org2/network-config.yaml:/FLLab/org/artifacts/network-config.yaml
      - ../org2/org.yaml:/FLLab/org/artifacts/org.yaml
      - ../org2/src/:/FLLab/org/artifacts/src/
      - ./channel-artifacts/channel.tx:/FLLab/org/artifacts/channel/channel.tx
      - ./crypto-config/:/FLLab/org/artifacts/channel/crypto-config/
      - ./bootstrap.sh:/FLLab/org/bootstrap.sh
    environment:
      - NODE_ROLE=join
      - NODE_NAME=peer0
      - NODE_ORG=Org2
      - NODE_INIT_USER=Jim2
      - NODE_FULLNAME=peer0.org2.example.com
        
    working_dir: /FLLab/org
    command: /bin/bash bootstrap.sh 

  org3_sdk:
    container_name: org3_sdk
    image: fabric/sdk:0.1
    ports:
      - 4002:4000
    volumes:
      - ../org3/network-config.yaml:/FLLab/org/artifacts/network-config.yaml
      - ../org3/org.yaml:/FLLab/org/artifacts/org.yaml
      - ../org3/src/:/FLLab/org/artifacts/src/
      - ./channel-artifacts/channel.tx:/FLLab/org/artifacts/channel/channel.tx
      - ./crypto-config/:/FLLab/org/artifacts/channel/crypto-config/
      - ./bootstrap.sh:/FLLab/org/bootstrap.sh
    environment:
      - NODE_ROLE=join
      - NODE_NAME=peer0
      - NODE_ORG=Org3
      - NODE_INIT_USER=Jim3
      - NODE_FULLNAME=peer0.org3.example.com
    working_dir: /FLLab/org
    command: /bin/bash bootstrap.sh 

